### ISSUE TITLE
Output to string variable

### ISSUE THREAD

**Issue by MaximilianJHuber** [jmboehm/RegressionTables.jl#7]
Is there a way to output the generated LaTeX/HTML code to a string? 
I want to call
`display("text/html", str)`
in my Jupyter notebook.

Right now, I would save to a file and read it in again, but that is inconvenient.

**Comment by jmboehm** [comment]
Hi Max,
I agree that it would be better if `regtable()` were to direct output to an `IOStream`. I'll add that in the next version. In the meantime, you can redirect STDOUT to a string using `redirect_stdout()`. See https://thenewphalls.wordpress.com/2014/03/21/capturing-output-in-julia/

**Comment by jmboehm** [comment]
Fixed by #13. You can do
```julia
my_buffer = IOBuffer()
regtable(rr1,rr2,rr3,rr4; renderSettings = asciiOutput(), out_buffer = my_buffer)
output_string = Compat.String(my_buffer)
```

**Comment by MaximilianJHuber** [comment]
Sorry, for taking so long to try it out. 

The behavior is still not good. 
Calling:
```
regtable(rr1,rr2,rr3,rr4; renderSettings = asciiOutput(), out_buffer = my_buffer)
```
still [prints](https://github.com/jmboehm/RegressionTables.jl/blob/1c1c4ac2dfe495607e7cbd5d65d2b8d17bed8039/src/regtable.jl#L401) out the output in a Jupyter Notebook. If I specify an output file (to circumvent the print) the IOBuffer comes back empty.

**Comment by jmboehm** [comment]
I don't have Jupyter, so can't try this myself. Does the
```
display("text/html", str)
```
part work? If yes, an option to avoid printing the table would solve the problem, no?

**Comment by MaximilianJHuber** [comment]
Yes, that part works and yes that would solve the issue.On Jan 22, 2019 06:23, Johannes Boehm <notifications@github.com> wrote:I don't have Jupyter, so can't try this myself. Does the
display("text/html", str)

part work? If yes, an option to avoid printing the table would solve the problem, no?
